### PR TITLE
WIP: x86 version of boot2docker.iso

### PR DESCRIPTION
**Pull request by StefanScherer**
This is a work in progress to create a 32bit version of the boot2docker.iso.

Why? Because I want a `boot2docker.iso` for AppVeyor CI to run integration tests of `docker-machine` there. Cloud CI slaves often lack of nested hypervisor functionality. But they can spin up 32bit VM's.

See also:
- https://github.com/docker/docker/issues/136
- https://github.com/boot2docker/boot2docker/issues/620
- https://github.com/docker/docker/issues/20004
- https://github.com/docker/docker/issues/20012
- Blog post: https://stefanscherer.github.io/how-to-create-a-32bit-boot2docker-for-x86-cpus/
- ...
- [x] missing 32bit version of docker at https://get.docker.com/builds/Linux/x86/docker-1.9.1
  - [x] WIP in PR StefanScherer/docker#1
- [x] missing 32bit version of docker at https://get.docker.com/builds/Linux/x86/docker-1.10.1
  - [x] WIP in PR StefanScherer/docker#2
- [ ] missing 32bit version at https://github.com/SvenDowideit/generate_cert/releases/tag/0.2
- [x] docker-machine must be able to set the NIC type to Am79C973 ( `--nictype1 "Am79C973"` ) as found in [AppVeyor discussion](http://help.appveyor.com/discussions/problems/1247-vagrant-not-working-inside-appveyor#comment_39277805)
  - [x] WIP in PR https://github.com/docker/machine/pull/3124
- [x] **first "working" AppVeyor build** https://ci.appveyor.com/project/StefanScherer/boot2docker/build/44

The PR just show the diffs, for an official PR there should be something like `Dockerfile.i386`...

### CODE REVIEW

**Comment by StefanScherer** [comment]
Problem with vmware/open-vm-tools:

```
make[2]: Entering directory '/open-vm-tools/lib/backdoor'
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.0\" -DPACKAGE_STRING=\"open-vm-tools\ 10.0.0\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DDNET_IS_DUMBNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I.   -I/open-vm-tools/lib/include -I/open-vm-tools/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE  -Wno-implicit-function-declaration -MT backdoor.lo -MD -MP -MF .deps/backdoor.Tpo -c -o backdoor.lo backdoor.c
libtool: compile:  gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.0\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.0\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DDNET_IS_DUMBNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I. -I/open-vm-tools/lib/include -I/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -Wno-implicit-function-declaration -MT backdoor.lo -MD -MP -MF .deps/backdoor.Tpo -c backdoor.c  -fPIC -DPIC -o .libs/backdoor.o
libtool: compile:  gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.0\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.0\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DDNET_IS_DUMBNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I. -I/open-vm-tools/lib/include -I/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -Wno-implicit-function-declaration -MT backdoor.lo -MD -MP -MF .deps/backdoor.Tpo -c backdoor.c -o backdoor.o >/dev/null 2>&1
mv -f .deps/backdoor.Tpo .deps/backdoor.Plo
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.0\" -DPACKAGE_STRING=\"open-vm-tools\ 10.0.0\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DDNET_IS_DUMBNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I.   -I/open-vm-tools/lib/include -I/open-vm-tools/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE  -Wno-implicit-function-declaration -MT backdoorGcc64.lo -MD -MP -MF .deps/backdoorGcc64.Tpo -c -o backdoorGcc64.lo backdoorGcc64.c
libtool: compile:  gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.0\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.0\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DDNET_IS_DUMBNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I. -I/open-vm-tools/lib/include -I/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -Wno-implicit-function-declaration -MT backdoorGcc64.lo -MD -MP -MF .deps/backdoorGcc64.Tpo -c backdoorGcc64.c  -fPIC -DPIC -o .libs/backdoorGcc64.o
[91mbackdoorGcc64.c: In function 'Backdoor_InOut':
[0m[91mbackdoorGcc64.c:78:4: error: PIC register clobbered by 'rbx' in 'asm'
    __asm__ __volatile__(
    ^
[0m[91mbackdoorGcc64.c: In function 'BackdoorHbIn':
[0m[91mbackdoorGcc64.c:144:4: error: PIC register clobbered by 'rbx' in 'asm'
    __asm__ __volatile__(
    ^
[0m[91mbackdoorGcc64.c: In function 'BackdoorHbOut':
backdoorGcc64.c:197:4: error: PIC register clobbered by 'rbx' in 'asm'
    __asm__ __volatile__(
    ^
[0mMakefile:460: recipe for target 'backdoorGcc64.lo' failed
make[2]: Leaving directory '/open-vm-tools/lib/backdoor'
[91mmake[2]: *** [backdoorGcc64.lo] Error 1
```

**Comment by StefanScherer** [comment]
A small breakthrough: In an AppVeyor RDP debug session I was able to spin up the boot2docker 32bit VM and pulled a first 32bit docker image and run a container on it.

2016-02-02_boot2docker_in_appveyor

```
docker pull 32bit/ubuntu:14.04
docker run -it 32bit/ubuntu:14.04 bash
```

2016-02-02_0752-docker-run-32bit-ubuntu-14 04

2016-02-02_0752-virtualbox-manager-b2d-appveyor

**Comment by StefanScherer** [comment]
To try it manually use 

```
 docker-machine -D create -d virtualbox --virtualbox-boot2docker-url https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/boot2docker.iso dev
```

**Comment by friism** [comment]
Dude, this is cool. It would also let us do smoke-test integration tests on cloud-hosted Windows VMs.

**Comment by StefanScherer** [comment]
I tested the boot2docker.iso with a patched docker-machine linux binary (to really turn off VT-X checks, sending another PR https://github.com/docker/machine/pull/3018 for this) inside TravisCI with this `.travis.yml`:

``` yaml
sudo: required
services:
  - docker
language: bash
script:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian vivid contrib" | sudo tee -a /etc/apt/sources.list
  - wget https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install linux-headers-$(uname -r)
  - sudo apt-get -y install virtualbox-5.0
  - sudo curl -L -o /usr/local/bin/docker-machine https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/docker-machine-Linux-x86_64
  - sudo chmod +x /usr/local/bin/docker-machine
  - docker-machine -D create -d virtualbox --virtualbox-no-vtx-check --virtualbox-boot2docker-url https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/boot2docker.iso dev || true
  - VBoxManage controlvm dev screenshotpng screenshot.png
  - docker-machine ls
```

I took a screenshot of the docker machine VM and it boots up and configures everything.

screenshot-2

Only problem is SSHing into the VM, so docker-machine will abort after 60 retries.

Same problem with AppVeyor and this `appveyor.yml`:

``` yaml
version: "{build}"

build_script:
  - AppVeyor DownloadFile http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-Win.exe
  - .\VirtualBox-5.0.14-105127-Win.exe -s -l -msiparams ADDLOCAL=VBoxApplication,VBoxUSB,VBoxNetworkAdp REBOOT=ReallySuppress
  - AppVeyor DownloadFile https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/docker-machine-Windows-x86_64.exe
  - copy docker-machine-Windows-x86_64.exe docker-machine.exe

test_script:
  - .\docker-machine.exe -D create -d virtualbox --virtualbox-no-vtx-check --virtualbox-boot2docker-url https://github.com/StefanScherer/boot2docker/releases/download/v1.9.1-386/boot2docker.iso dev
```

**Pull request closed without merging**
